### ISSUE TITLE
[analytics] Tracking segment events for dApps on home screen

### ISSUE THREAD

**Issue by grvalora** [valora-inc/wallet#1965]
### Description
Need tracking for the dApps Listed on the home screen

### User Stories 
In order to fully understand the user interaction to the dapp page, requesting the following events. 
we already have the following 
- [ ] 1. **view_all_dapps** : when user clicks on the View all dapps toggle on the homescreen
- [ ] 2. **dapp_home_impression** : when dapps are shown in home screen. Send one event for one dapp
- [ ] 3. **dapp_home_click** : when user clicks on the dapp in the bottom sheet

For the events from 2-4 please include the following parameters. 

- [ ]  categoryId: string
- [ ]   dappId: string
- [ ]   dappName: string
- [ ]   section: string ( can be home screen or recently used) 
- [ ]   horizontalPosition: number

----- Exception -------
- [ ]  **Note:** Incase of Bidali, where no alert is shown due to web app, please fire both dapp_click and dapp_open at clicking the dapp.
