### ISSUE TITLE
Prepare for Celo phone verification v2

### ISSUE THREAD

**Issue by silasbw** [valora-inc/wallet#2380]
clabs is (has?) deprecated phone verification v1 and is planning a replacement.  We (Valora) have also experienced user pains around phone verification.  For example, the success rate in Turkey is close to 0 and the highest success rate is less than 90%.  This has presented friction for key experiences, like onboarding or becoming eligible for supercharge and has restricted the markets that Valora can be successful in. 

This epic is focused on replacing phone verification v1 with centralized phone verification ("Valora phone verification") which should lay the foundation for moving to Celo phone verification v2.

CLabs plan doc [here](https://clabsco.notion.site/Federated-Attestation-Protocol-ASv2-05dc4843139842768ad9fe192cb46c00)

ENG:
- [ ] consider verification-as-a-service options for the MVP of Valora verification (_e.g._, https://www.twilio.com/verify)

AC:
- [ ] Valora phone verification requires one SMS txt message
- [ ] It's practically difficult to query all phone numbers to get a list of wallet addresses (e.g., ODIS-like rate limit) 
- [ ] Updates to supercharge to distribute rewards for numbers verified with Valora phone verification or Celo phone verification v1
- [ ] Design review from clabs identity team to comment on the efficacy of Valora phone verification in relation to Celo phone verification v2 (or what clabs sometimes calls proof of identity/individuality)
- [ ] A plan for replacing (or ceasing support for) escrow
- [ ] Instrumentation that gives us the ability to compare verification success rates between Celo phone verification v1 and Valora phone verification
- [ ] Updates to the wallet to use Valora phone verification
